services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_integration_test:
    image: postgres:17
    container_name: postgres_integration_test
    restart: unless-stopped
    environment:
      POSTGRES_DB: gobootstrapweb_test
      POSTGRES_USER: integration_user
      POSTGRES_PASSWORD: integration_password
    ports:
      - "5433:5432"

volumes:
  postgres_data:
