// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_reset_requests.sql

package db

import (
	"context"
)

const consumeEmailResetRequest = `-- name: ConsumeEmailResetRequest :one
DELETE FROM email_reset_requests
WHERE id = $1
RETURNING id, user_id, new_email, created_at
`

func (q *Queries) ConsumeEmailResetRequest(ctx context.Context, id []byte) (EmailResetRequest, error) {
	row := q.db.QueryRow(ctx, consumeEmailResetRequest, id)
	var i EmailResetRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewEmail,
		&i.CreatedAt,
	)
	return i, err
}

const createEmailResetRequest = `-- name: CreateEmailResetRequest :one
INSERT INTO email_reset_requests (
  id, user_id, new_email
) VALUES ( $1, $2, $3 )
RETURNING id, user_id, new_email, created_at
`

type CreateEmailResetRequestParams struct {
	ID       []byte
	UserID   int64
	NewEmail string
}

func (q *Queries) CreateEmailResetRequest(ctx context.Context, arg CreateEmailResetRequestParams) (EmailResetRequest, error) {
	row := q.db.QueryRow(ctx, createEmailResetRequest, arg.ID, arg.UserID, arg.NewEmail)
	var i EmailResetRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewEmail,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmailResetRequestsForUser = `-- name: DeleteEmailResetRequestsForUser :exec
DELETE FROM email_reset_requests
WHERE user_id = $1
`

func (q *Queries) DeleteEmailResetRequestsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteEmailResetRequestsForUser, userID)
	return err
}
