// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthAction string

const (
	AuthActionLogin            AuthAction = "login"
	AuthActionPasswordReset    AuthAction = "password_reset"
	AuthActionEmailReset       AuthAction = "email_reset"
	AuthActionReauthentication AuthAction = "reauthentication"
)

func (e *AuthAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthAction(s)
	case string:
		*e = AuthAction(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthAction: %T", src)
	}
	return nil
}

type NullAuthAction struct {
	AuthAction AuthAction
	Valid      bool // Valid is true if AuthAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthAction) Scan(value interface{}) error {
	if value == nil {
		ns.AuthAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthAction), nil
}

type AuthOutcome string

const (
	AuthOutcomeSucceeded AuthOutcome = "succeeded"
	AuthOutcomeFailed    AuthOutcome = "failed"
)

func (e *AuthOutcome) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthOutcome(s)
	case string:
		*e = AuthOutcome(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthOutcome: %T", src)
	}
	return nil
}

type NullAuthOutcome struct {
	AuthOutcome AuthOutcome
	Valid       bool // Valid is true if AuthOutcome is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthOutcome) Scan(value interface{}) error {
	if value == nil {
		ns.AuthOutcome, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthOutcome.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthOutcome) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthOutcome), nil
}

type AuthAttempt struct {
	ID        int64
	Action    AuthAction
	Email     string
	CreatedAt pgtype.Timestamptz
	Outcome   AuthOutcome
}

type EmailResetRequest struct {
	ID        []byte
	UserID    int64
	NewEmail  string
	CreatedAt pgtype.Timestamptz
}

type PasswordResetRequest struct {
	ID        []byte
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID              []byte
	UserID          int64
	CreatedAt       pgtype.Timestamptz
	LastSeenAt      pgtype.Timestamptz
	LastRefreshedAt pgtype.Timestamptz
	IsActive        bool
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	SignedUpAt   pgtype.Timestamptz
	IsActive     bool
}
