// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailResetRequest struct {
	ID        []byte
	UserID    int64
	NewEmail  string
	CreatedAt pgtype.Timestamptz
}

type PasswordResetRequest struct {
	ID        []byte
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID         []byte
	UserID     int64
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	SignedUpAt   pgtype.Timestamptz
	IsActive     bool
}
