// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID                []byte
	UserID            int64
	CreatedAt         pgtype.Timestamptz
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	RenewalExpiresAt  pgtype.Timestamptz
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	SignedUpAt   pgtype.Timestamptz
	IsActive     bool
}
