// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset_requests.sql

package db

import (
	"context"
)

const consumePasswordResetRequest = `-- name: ConsumePasswordResetRequest :one
DELETE FROM password_reset_requests
WHERE id = $1
RETURNING id, user_id, created_at
`

func (q *Queries) ConsumePasswordResetRequest(ctx context.Context, id []byte) (PasswordResetRequest, error) {
	row := q.db.QueryRow(ctx, consumePasswordResetRequest, id)
	var i PasswordResetRequest
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}

const createPasswordResetRequest = `-- name: CreatePasswordResetRequest :one
INSERT INTO password_reset_requests (
  id, user_id
) VALUES ( $1, $2 )
RETURNING id, user_id, created_at
`

type CreatePasswordResetRequestParams struct {
	ID     []byte
	UserID int64
}

func (q *Queries) CreatePasswordResetRequest(ctx context.Context, arg CreatePasswordResetRequestParams) (PasswordResetRequest, error) {
	row := q.db.QueryRow(ctx, createPasswordResetRequest, arg.ID, arg.UserID)
	var i PasswordResetRequest
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}

const deletePasswordResetRequestsForUser = `-- name: DeletePasswordResetRequestsForUser :exec
DELETE FROM password_reset_requests
WHERE user_id = $1
`

func (q *Queries) DeletePasswordResetRequestsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deletePasswordResetRequestsForUser, userID)
	return err
}
