// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    user_id
) VALUES (
    $1,
    $2
)
RETURNING id, user_id, created_at, last_seen_at, last_refreshed_at
`

type CreateSessionParams struct {
	ID     []byte
	UserID int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.LastRefreshedAt,
	)
	return i, err
}

const deleteSessionByID = `-- name: DeleteSessionByID :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSessionByID(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, deleteSessionByID, id)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, created_at, last_seen_at, last_seen_at
FROM sessions
WHERE id = $1
`

type GetSessionByIDRow struct {
	ID           []byte
	UserID       int64
	CreatedAt    pgtype.Timestamptz
	LastSeenAt   pgtype.Timestamptz
	LastSeenAt_2 pgtype.Timestamptz
}

func (q *Queries) GetSessionByID(ctx context.Context, id []byte) (GetSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.LastSeenAt_2,
	)
	return i, err
}
