// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    user_id
) VALUES (
    $1,
    $2
)
RETURNING id, user_id, created_at, last_seen_at
`

type CreateSessionParams struct {
	ID     []byte
	UserID int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const deleteAllSessionsForUser = `-- name: DeleteAllSessionsForUser :exec
DELETE FROM sessions
WHERE user_id = $1
`

func (q *Queries) DeleteAllSessionsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAllSessionsForUser, userID)
	return err
}

const deleteLeastRecentlyUsedSessionForUser = `-- name: DeleteLeastRecentlyUsedSessionForUser :exec
DELETE FROM sessions
WHERE id = (
  SELECT s.id
  FROM sessions s
  WHERE s.user_id = $1
  ORDER BY s.last_seen_at ASC
  LIMIT 1
)
`

func (q *Queries) DeleteLeastRecentlyUsedSessionForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteLeastRecentlyUsedSessionForUser, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT s.id, s.user_id, s.created_at, s.last_seen_at
FROM sessions s
JOIN users u on s.user_id = u.id 
WHERE s.id = $1 AND u.is_active = TRUE
`

func (q *Queries) GetSession(ctx context.Context, id []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getSessionCountByUser = `-- name: GetSessionCountByUser :one
SELECT COUNT(*)
FROM sessions
WHERE user_id = $1
`

func (q *Queries) GetSessionCountByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getSessionCountByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateSessionLastSeenToNow = `-- name: UpdateSessionLastSeenToNow :one
UPDATE sessions
SET last_seen_at = NOW()
WHERE id = $1
RETURNING id, user_id, created_at, last_seen_at
`

func (q *Queries) UpdateSessionLastSeenToNow(ctx context.Context, id []byte) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionLastSeenToNow, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
