-- +goose Up
CREATE EXTENSION IF NOT EXISTS citext;

-- TODO: Switch to identity primary key columns
-- it is the sql standard.
-- GENERATED BY ...
CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    email CITEXT NOT NULL UNIQUE CHECK (char_length(email) BETWEEN 1 AND 320),
    password_hash VARCHAR(255) NOT NULL,
    signed_up_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_active BOOLEAN NOT NULL DEFAULT TRUE

);

CREATE TABLE sessions (
    id BYTEA PRIMARY KEY CHECK (octet_length(id) = 32), -- SHA-256 of session id
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_refreshed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (created_at <= last_seen_at),
    CHECK (created_at <= last_refreshed_at)
);


CREATE INDEX idx_sessions_user
ON sessions(user_id);

CREATE INDEX idx_sessions_user_last_seen
ON sessions(user_id, last_seen_at, id);

-- +goose Down
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
